=== Julia-JB/BikeRentalJDBC/bike_rental/my-bike-rental/src/main/java/xmlValidation/resources/rentalTransactions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="rentalTransactions" type="RentalTransactionsType"/>

    <xs:complexType name="RentalTransactionsType">
        <xs:sequence>
            <xs:element name="transaction" type="TransactionType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TransactionType">
        <xs:sequence>
            <xs:element name="transactionId" type="xs:int"/>
            <xs:element name="dateTime" type="xs:dateTime"/>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="amount" type="xs:decimal"/>
            <xs:element name="userId" type="xs:int"/>
            <xs:element name="rentalId" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Julia-JB/BikeRentalJDBC/bike_rental/my-bike-rental/src/main/java/xmlValidation/resources/rentalTransactions.xml
<?xml version="1.0" encoding="UTF-8"?>
<rentalTransactions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance rentalTransactions.xsd ">
    <rentalTransactions>
        <transaction>
            <transactionId>1</transactionId>
            <dateTime>2023-05-30T10:50:00</dateTime>
            <type>Cash</type>
            <amount>0.24</amount>
            <userId>2</userId>
            <rentalId>1</rentalId>
        </transaction>
        <transaction>
            <transactionId>5</transactionId>
            <dateTime>2023-05-14T10:58:00</dateTime>
            <type>Credit card</type>
            <amount>0.40</amount>
            <userId>3</userId>
            <rentalId>4</rentalId>
        </transaction>
</rentalTransactions>
